class fkt {
//You are given two strings s and t.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Return the letter that was added to t.  


public static void main(String[] args) {
      
        String S="ABCDEFGH";
        String K="ABCDETFGH";
        int xor=0;
      int Slen=S.length();
      int Klen=K.length();
      
      for(int i=0; i<Slen;i++){
      xor=xor^ ((int)S.charAt(i));}
      
      for(int i1=0; i1<Klen;i1++){
      xor=xor^ ((int)K.charAt(i1));}
      
      System.out.println((char)xor);
      

      

        
    }
}
